version: '3.8'

services:
  elasticsearch:
    image: bitnami/elasticsearch
    volumes:
      - /elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      ELASTIC_PASSWORD: changeme
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    image: logstash:8.13.0
    volumes:
      - /elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /elk/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - MOU_HOST=192.168.248.20
    ports:
      - "5000:5000"
      - "9600:9600"
      - "15044:15044"
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image:  bitnami/kibana
    volumes:
      - /elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    environment:
      - MOU_HOST=192.168.248.20
    depends_on:
      - elasticsearch
    networks:
      - elk

  nginx:
    image: nginx:latest
    volumes:
      - /elk/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /elk/nginx/log:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - elk

  filebeat:
    image: elastic/filebeat:7.17.19
    entrypoint: "filebeat -e -strict.perms=false"
    user: root
    volumes:
      - /elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /elk/nginx/log:/var/log/nginx
    depends_on:
      - nginx
      - logstash
      - elasticsearch
      - kibana
    networks:
      - elk
    links:
      - logstash

  zookeeper:
    image: zookeeper:3.9.2-jre-17
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - elk

  kafka:
    image: ubuntu/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /elk/kafka/config/server.properties:/opt/kafka/config/server.properties
      - /elk/kafka/config/log4j.properties:/opt/kafka/config/log4j.properties
      - /elk/kafka/logs:/var/lib/kafka/logs
      - /elk/kafka/config/kafka-log4j-appender-3.5.1.jar:/opt/kafka/libs/kafka-log4j-appender.jar
    networks:
      - elk


networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
